url::/home/waldelf/Documents##False
url::/home/waldelf##False
url::/home/lifebuilder##True
actionrestriction::action/file_new
actionrestriction::action/file_open
actionrestriction::action/file_open_recent
actionrestriction::action/file_save_as
module::formats.desktop
module::style.desktop
